import Head from "next/head"
import Layout from "./layout/Layout"
import PasswordGeneratorForm from "./PasswordGeneratorForm"

export default function Home() {
    return <Layout>
    <Head>
      <title>Generate password</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main >
      <PasswordGeneratorForm />
    </main>
  </Layout>
}