import Head from "next/head"
// import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Layout from "../layout/Layout"

export default function Home() {
    return <Layout>
    <Head>
      <title>Generate password</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main >
      <h2>Generate password:</h2>
    </main>
  </Layout>
}